### PR TITLE
Fix append unique

### PR DESCRIPTION
**Pull request by crutchcorn**
Built upon #139 but adds tests and breaks regex out to its own variable

### CODE REVIEW

**Comment by crutchcorn** [comment]
@gustaff-weldon I seem to recall there being some mild issue with the logic somewhere. Do you mind doing a quick test for me on your project to see if the issue was solved?

If we can verify this fixes the problem, I'm happy to merge and make a deploy within the hour. If not, it might have to wait a few days until I can dedicate some time to verify tests pass (and fail) as expected/etc

--------

# Setup Instructions

Can you clone this project (`node-plop`), `npm i`, then `npm compile` and `npm link`. This will make it so that you can use `node-plop` on your local machine

Then, [clone `plop`](https://github.com/plopjs/plop), run `npm i`, then `npm link node-plop` (which will pull your local instance into `node_modules`. Finally, run `npm link` (from within `plop` root, OFC). 

After this `plop` should be coming from a local install (you can verify this by [changing the `package version`](https://github.com/plopjs/plop/blob/master/package.json#L3) before `npm link`ing `plop`

**Comment by crutchcorn** [comment]
> @crutchcorn, I have tested this (verified it's linked properly) and it still does not work.
> Screenshot 2021-10-19 at 22 08 45
> 
> I have provided the reproduction case for this bug in the linked comment above.

Thanks a ton for testing (and providing repro). I'll be taking a look at this sometime later this week

**Comment by gustaff-weldon** [comment]
Looking at the changes you've made they seem to apply only when `unique` is set. Is this set to `true` by default? I'm not passing this to `append`":
```
        {
          type: 'append',
          path: '../.github/monorepo.yml',
          templateFile: 'spring-boot/.github/monorepo.yml'
        },
```
Also, is there a way to run plop in verbose mode? I'd like to see the actual error that happened with the exact action and line that triggered it.


Maybe this will help:
```
export const springBoot = () => {
  return {
    description: 'Adds deployment configuration for a service',
    prompts: [ 
      {
        type: 'input',
        name: 'serviceName',
        message: 'Service name',
        validate: (input: string) => !!input
      }
    ],
    actions: [
      {
        type: 'append',
        path: '../.github/monorepo.yml',
        templateFile: 'spring-boot/.github/monorepo.yml'
      },
    ]
  };
}

export default function(plop) {
  plop.setGenerator('Spring Boot deployment generator', springBoot());
};
```
spring-boot/.github/monorepo.yml
```
  {{serviceName}}:
    depends_on:
      files:
        - "deployment-templates/spring-boot/**/*"

    required_checks:
      - build
      - test
```

**Comment by crutchcorn** [comment]
This PR has been migrated to our new Plop monorepo

https://github.com/plopjs/plop/pull/330

**Pull request closed without merging**
