### PR TITLE
Expose plop.setGenerator()

### PR DESCRIPTION
**Pull request by brian428**
Make plop file optional, and expose plop.setGenerator() function to allow dynamic creation of generator configs.

### CODE REVIEW

**Comment by brian428** [comment]
In fact, it probably makes sense to expose the other internal plop fields (inquirer, handlebars, addPrompt, etc.)? I can modify the pull request to add these if you like.

**Comment by amwmedia** [comment]
yeah, I like the overall idea of being able to use plop without a plopfile. 

good idea 👍

**Comment by brian428** [comment]
It's very handy. I've already manually tweaked the node-plop index to expose the other functions, and have already incorporated some generation logic into my gulp build. And it's all code (and dynamic), so no plopfiles. :-)

**Comment by amwmedia** [comment]
@brian428 when you use this approach, do you have to specify absolute paths for the templateFiles and paths, or do you set the `plopfilePath` later in order to set your context path?

**Comment by brian428** [comment]
I've got it working just using paths relative from the project root, which is basically the "current directory" while the gulp tasks run. Does that answer your question?

**Comment by amwmedia** [comment]
yeah, makes sense. The `plopfilePath` concept was added so if your ran the `plop` cli from a subfolder, files would still be created in the correct place. But I suppose when you're using automation in a script, you can always set the cwd in the script if needed.

**Pull request merged**
