### PR TITLE
enable adding data property to action definition

### PR DESCRIPTION
**Pull request by macrozone**
Now you can add a `data` object to an action definitions. This data gets merged with the user-data.

I was not sure whether user-data should override action data or vis-verca. But i think, that user-data overrides the action data makes slightly more sense. 

fixes https://github.com/amwmedia/plop/issues/88

### CODE REVIEW

**Comment by amwmedia** [comment]
merging this... docs available in the [v2 release prep branch](https://github.com/amwmedia/plop/tree/feature/v2#interface-actionconfig)

**Comment by platonish** [comment]
Hi, I'm new to plop and know very little Node.js. I'm trying to use this feature, I'm not able to figure out how:
```
actions: [{
      type: 'add',
      path: 'src/{{directory}}/{{pascalCase name}}Component.jsx',
      templateFile: 'templates/component.hbs',
      data: {
        name: '{{pascalCase name}}Component'
      }
    },
   ...
]
```
What am I doing wrong? I want to append `Component` to the name before passing it to the template, since there are other actions which use the name as is. Thanks in advance!

**Comment by amwmedia** [comment]
to append a string to the end of the input you would normally just add it to the template (just like you did in your example for the `path` value. If you want the word component to be dynamic so you can use the same `templateFile` for other actions as well you can add another property to the `data` object and use it in your template.

example: 
``` javascript
actions: [{
      type: 'add',
      path: 'src/{{directory}}/{{pascalCase name}}{{pascalCase nameSuffix}}.jsx',
      templateFile: 'templates/component.hbs',
      data: {
        nameSuffix: 'Component'
      }
    },
   ...
]
```

**Comment by platonish** [comment]
Thanks, this works! A simple solution!

**Pull request merged**
