### PR TITLE
Dynamic prompts

### PR DESCRIPTION
**Pull request by filipemir**
Issue: #36 

This change adds support for inquirer's hierarchical prompts. For an example, see here: https://github.com/SBoudrias/Inquirer.js/blob/master/examples/hierarchical.js

### CODE REVIEW

**Comment by amwmedia** [comment]
wow, that really was pretty easy to implement 👍

**Comment by filipemir** [comment]
Yeah, I was pretty happy with how easily that went too. Let me know if you need any other changes.

**Comment by filipemir** [comment]
Hello. Any update on when this PR might be merged? Let me know if I can help with anything

**Comment by amwmedia** [comment]
@filipemir are you on twitter? if so, what's your account? I like to give a shout out to contributors when I release a new version of plop. :-)

**Comment by filipemir** [comment]
Thanks, @amwmedia. I am not on twitter but thanks for asking :)

**Comment by jjwinskill** [comment]
@amwmedia any chance of adding docs for dynamic prompts?

**Comment by amwmedia** [comment]
@jjwinskill we don't currently document inquirer features in the plop documentation. We simply say that inquirer prompts are used and point people to where to find the corresponding docs. 

I wouldn't be opposed to having a short blurb about this and linking over to where to find the detailed docs. Any thoughts on where that blurb should live?

**Comment by jjwinskill** [comment]
I was thinking it would make sense actually outside of node-plop. Specifically, if this is an available feature then I think it makes sense to include a simple "how to use" blurb right above dynamic actions in the plop repository [here](https://github.com/amwmedia/plop#using-a-dynamic-actions-array)

**Comment by amwmedia** [comment]
@jjwinskill care to take a stab at what that might look like and submit a PR?

**Pull request merged**
