### PR TITLE
Allow control over globby using addMany

### PR DESCRIPTION
**Pull request by tkvw**
This PR allows templateFiles of addMany to be a function. Usage:
```
{
      type: 'addMany',
      destination: '{{destination}}',
      base: 'templates/javascript/library/rollup',
      templateFiles: globbySync => globbySync('templates/javascript/library/rollup/**/*',{dot:true})
}
```
Globbysync is not globby directly, but a wrapper to `globby.sync`. The `cwd` option is still set. 
`data,cfg,plop` are also passed as parameters. `(globbySync,data,cfg,plop)=>..`
Also: the resulting patterns are still rendered by plop. 

I also changed the validation of isFile, because it depended on an extension being available and that is not a requirement for a file. 

I think this solves https://github.com/amwmedia/node-plop/issues/48 , check the test for this use case.

### CODE REVIEW

**Comment by amwmedia** [comment]
Thanks Dennie @tkvw!

What benefit do you see in having `templateFiles` handled as a function that receives `globbySync` vs having a `globbyOptions` property available on the action config object? I kind of like the idea of allowing the templateFiles array to be dynamic (via a function), but I think we could do that without needing to pass around globby functions too. 

Thoughts?

**Comment by tkvw** [comment]
If you don't want to use a function then a `globbyOptions` parameter should suffice indeed. 
But if you want to allow a function I think this is the way to do it. The user probably wants to use globby to resolve files and you want to make sure sync is used and that the `cwd` parameter is setup correctly.

**Comment by amwmedia** [comment]
I see what you mean. My thinking is that there's already an expectation that the array of strings defined here will be run through globby, so I think that returning the globby patterns from that function would probably be adequate. That still gives all the control of how globby is executed (sync vs async). The function approach could still be used to change what globby patterns to include based on prompt answers, so there could be benefits there.

@tkvw do you see additional benefits to the function that has globbySync injected that I'm missing?

**Comment by tkvw** [comment]
Yeah, so I changed it to your suggestion. All that counts for me is to have the globbyOptions available.

**Pull request merged**
