### PR TITLE
Fixes to binary copy logic

### PR DESCRIPTION
**Pull request by amwmedia**
@crutchcorn have a look

### CODE REVIEW

**Comment by crutchcorn** [comment]
This is much more verbose than how I went about things. Glad to see that things _more or less_ resemble the same general logic (but with better error handling/etc). Awesome work, better than how I had done it :+1: :D

**Comment by amwmedia** [comment]
still uses your basic approach, but the `isBinary.sync()` function was silently choking on actions that didn't have a `templateFile`.

**Comment by amwmedia** [comment]
that was why the tests were failing

**Comment by crutchcorn** [comment]
Oooooh. I wouldn't've even figured that one. Great catch, my bad :sweat_smile:

**Pull request merged**
