### PR TITLE
Unwanted action data persistence #89

### LINKED ISSUE #89: Unwanted action data persistence
Sometimes one does not want to have a single file with `each`, but wants multiple files instead.  
In the example below I try to render the same template multiple times but with the different data.  `parents` is an array produced by `checkbox` prompt.

```js
const actions = _.map(parents, parent => ({
  type: 'add',
  path: `migrations/model_belongs_to_${parent}.js`,
  templateFile: `templates/belongs_to.hbs`,
  data: { parent },
})),
```

In my case the generated files have the same `parent` value -- the first one from the array.

It seems this commit https://github.com/amwmedia/node-plop/commit/ac4bcc4c0ab23d4812fc69f31105b8305b5d2e0a has "fixed" such a behavior.  
I can fully understand why we prevent overwriting the answers gathered by inquirer, but that code does a bit more than that.

### PR DESCRIPTION
**Pull request by apurvaojas**
fix #89

### CODE REVIEW

**Comment by apurvaojas** [comment]
The data should override the answer, because the user can use `default` in prompt if it doesn't provide with answer. if user is passing data then it should override the old one.

**Comment by apurvaojas** [comment]
one solution can be, but in either case test case `custom-data-in-action` needs to be updated.
This solution looks more prominent, as each action should have its own data scope. 
 

```
const executeActionLogic = co.wrap(function* (action, cfg, data) {
		const type = cfg.type || '';
		const _data = {...data};
		// convert any returned data into a promise to
		// return and wait on
		let cfgData = cfg.data || {};
		// data can also be a function that returns a data object
		if (typeof cfgData === 'function') { cfgData = yield cfgData(); }
		Object.keys(cfgData || {}).forEach(k => {
			if (typeof data[k] === 'undefined') { 
				_data[k] = cfgData[k]; 
			}
		});
		return yield Promise.resolve(action(_data, cfg, plopfileApi)).then(
			// show the resolved value in the console
			result => ({
				type, path: (typeof result === 'string'
					? result
					: JSON.stringify(result)
				)
			}),
			// a rejected promise is treated as a failure
			function (err) {
				throw { type, path: '', error: err.message || err.toString() };
			}
		);
	});

```

**Comment by amwmedia** [comment]
Thanks for putting time into this. looks like your solution breaks some tests. I'm going to take a look today.

**Comment by apurvaojas** [comment]
Hi @amwmedia 

I have implemented the [option 3](https://github.com/amwmedia/plop/issues/145#issuecomment-467479549) suggested by you. Please merge and publish the package. I have dependency on this implementation.

Thanks

**Comment by amwmedia** [comment]
thanks for taking the time to implement this. I had actually implemented it already, added tests, etc. I evaluated both of our approaches and they had similar results.

**Pull request closed without merging**
